// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2632.testRobot1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Servo climbSystemsrightArm;
    public static Servo climbSystemsleftArm;
    public static SpeedController climbSystemsclimbingMotor;
    public static Servo climbSystemswhiskerRelease;
    public static SpeedController driveSystemleftFront;
    public static SpeedController driveSystemleftRear;
    public static SpeedController driveSystemrightFront;
    public static SpeedController driveSystemrightRear;
    public static RobotDrive driveSystemrobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        climbSystemsrightArm = new Servo(3);
        LiveWindow.addActuator("climbSystems", "rightArm", climbSystemsrightArm);
        
        climbSystemsleftArm = new Servo(1);
        LiveWindow.addActuator("climbSystems", "leftArm", climbSystemsleftArm);
        
        climbSystemsclimbingMotor = new Talon(0);
        LiveWindow.addActuator("climbSystems", "climbingMotor", (Talon) climbSystemsclimbingMotor);
        
        climbSystemswhiskerRelease = new Servo(2);
        LiveWindow.addActuator("climbSystems", "whiskerRelease", climbSystemswhiskerRelease);
        
        driveSystemleftFront = new Talon(7);
        LiveWindow.addActuator("driveSystem", "leftFront", (Talon) driveSystemleftFront);
        
        driveSystemleftRear = new Talon(4);
        LiveWindow.addActuator("driveSystem", "leftRear", (Talon) driveSystemleftRear);
        
        driveSystemrightFront = new Talon(5);
        LiveWindow.addActuator("driveSystem", "rightFront", (Talon) driveSystemrightFront);
        
        driveSystemrightRear = new Talon(6);
        LiveWindow.addActuator("driveSystem", "rightRear", (Talon) driveSystemrightRear);
        
        driveSystemrobotDrive = new RobotDrive(driveSystemleftFront, driveSystemleftRear,
              driveSystemrightFront, driveSystemrightRear);
        
        driveSystemrobotDrive.setSafetyEnabled(true);
        driveSystemrobotDrive.setExpiration(0.1);
        driveSystemrobotDrive.setSensitivity(0.5);
        driveSystemrobotDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
